require("user.lsp.servers.bashls")
require("user.lsp.servers.ccls")
require("user.lsp.servers.cmake")
require("user.lsp.servers.cssls")
--[[ require("user.lsp.servers.denols") ]]
require("user.lsp.servers.dockerls")
require("user.lsp.servers.eslint")
require("user.lsp.servers.gopls")
-- require("user.lsp.servers.hls")
require("user.lsp.servers.html")
require("user.lsp.servers.jsonls")
require("user.lsp.servers.lua_ls")
require("user.lsp.servers.omnisharp")
require("user.lsp.servers.pyright")
require("user.lsp.servers.rust_analyzer").setup()
require("user.lsp.servers.sqlls")
-- require("user.lsp.servers.sqls")
-- require("user.lsp.servers.tailwindcss")
require("user.lsp.servers.tsserver")
require("user.lsp.servers.vimls")
require("user.lsp.servers.yamlls")
