require("user.lsp.servers.bashls")
require("user.lsp.servers.buf_ls")
require("user.lsp.servers.ccls")
require("user.lsp.servers.clangd")
require("user.lsp.servers.cmake")
require("user.lsp.servers.cssls")
require("user.lsp.servers.denols")
require("user.lsp.servers.dockerls")
require("user.lsp.servers.eslint")
require("user.lsp.servers.gopls")
require("user.lsp.servers.hls")
require("user.lsp.servers.html")
require("user.lsp.servers.jsonls")
require("user.lsp.servers.lua_ls")
require("user.lsp.servers.omnisharp")
require("user.lsp.servers.prismals")
require("user.lsp.servers.pyright")
-- require("user.lsp.servers.rust_analyzer").setup()
require("user.lsp.servers.sqls")
require("user.lsp.servers.tailwindcss")
require("user.lsp.servers.ts_ls")
require("user.lsp.servers.vimls")
require("user.lsp.servers.yamlls")

-- vim.lsp.enable('bashls')
-- vim.lsp.enable('buf_ls')
-- vim.lsp.enable('ccls')
vim.lsp.enable('clangd')
-- vim.lsp.enable('cmake')
-- vim.lsp.enable('cssls')
-- vim.lsp.enable('denols')
-- vim.lsp.enable('dockerls')
-- vim.lsp.enable('eslint')
-- vim.lsp.enable('gopls')
-- vim.lsp.enable('hls')
-- vim.lsp.enable('html')
vim.lsp.enable('lua_ls')
-- vim.lsp.enable('omnisharp')
-- vim.lsp.enable('prismals')
-- vim.lsp.enable('pyright')
-- vim.lsp.enable('sqls')
-- vim.lsp.enable('tailwindcss')
-- vim.lsp.enable('ts_ls')
-- vim.lsp.enable('vimls')
-- vim.lsp.enable('yamlls')
