vim.api.nvim_set_keymap('', 't', "<cmd>lua require('hop').hint_words()<cr>", {})
vim.api.nvim_set_keymap('', 'T', "<cmd>lua require('hop').hint_lines()<cr>", {})
vim.api.nvim_set_keymap('', 'f', "<cmd>lua require('hop').hint_words({ inclusive_jump = true })<cr>", {})
vim.api.nvim_set_keymap('', 's', "<cmd>lua require('hop').hint_words({ current_line_only = true })<cr>", {})
-- vim.api.nvim_set_keymap('', 's', "<cmd>lua require('hop').hint_char1({ current_line_only = true })<cr>", {})
